import Link from "next/link";
import { getDraftPool } from "../../../lib/queries";

export const dynamic = "force-dynamic";

const formatNumber = (value) => value === null || value === undefined || Number.isNaN(Number(value)) ? "--" : Number(value).toFixed(1);

export default async function DraftPlayersPage({ searchParams }) {
  const params = searchParams || {};
  const filters = { conference: params.conference || "All", position: params.position || "All", team: params.team || "All", minPpg: params.min_ppg || "", maxPpg: params.max_ppg || "" };
  const view = params.view === "cards" ? "cards" : "table";
  const allPlayers = await getDraftPool(500);
  const players = await getDraftPool(500, filters);
  const conferences = [...new Set(allPlayers.map((player) => player.conference_name).filter(Boolean))].sort();
  const teams = [...new Set(allPlayers.map((player) => player.team_name).filter(Boolean))].sort();

  return <div className="page draft-players-page">
    <div className="draft-subnav"><Link href="/draft/board">Draft Board</Link><Link className="active" href="/draft/players">Player Focus</Link></div>
    <section className="draft-focus-hero"><div><span className="draft-countdown-kicker">Draft headquarters · Player focus</span><h1>Find the right player.</h1><p>Use the pool to research candidates before the off-site draft. The player board will gain headshots, drafted status, and deeper comparisons in later phases.</p></div><div className="draft-focus-count"><strong>{players.length}</strong><span>players in view</span></div></section>
    <form className="filters" method="get"><input type="hidden" name="view" value={view} /><div className="filter-card"><label>Conference</label><select name="conference" defaultValue={filters.conference}><option>All</option>{conferences.map((conference) => <option key={conference}>{conference}</option>)}</select></div><div className="filter-card"><label>Position</label><select name="position" defaultValue={filters.position}><option>All</option><option>G</option><option>F</option><option>C</option><option>G-F</option><option>F-C</option></select></div><div className="filter-card"><label>Team</label><select name="team" defaultValue={filters.team}><option>All</option>{teams.map((team) => <option key={team}>{team}</option>)}</select></div><div className="filter-card"><label>PPG range</label><div className="ppg-range"><input name="min_ppg" type="number" step="0.1" placeholder="Min" defaultValue={filters.minPpg} /><input name="max_ppg" type="number" step="0.1" placeholder="Max" defaultValue={filters.maxPpg} /></div></div><div className="filter-card filter-submit"><button className="solid-pill" type="submit">Apply filters</button><Link className="ghost-pill" href="/draft/players">Reset</Link></div></form>
    <section className="card"><div className="section-title"><div><h2>Player pool</h2><span className="section-subtitle">Research view · Drafted status comes later</span></div><div className="draft-board-toggle"><Link className={view === "table" ? "active" : ""} href={`/draft/players?view=table&conference=${encodeURIComponent(filters.conference)}&position=${encodeURIComponent(filters.position)}&team=${encodeURIComponent(filters.team)}&min_ppg=${filters.minPpg}&max_ppg=${filters.maxPpg}`}>Table</Link><Link className={view === "cards" ? "active" : ""} href={`/draft/players?view=cards&conference=${encodeURIComponent(filters.conference)}&position=${encodeURIComponent(filters.position)}&team=${encodeURIComponent(filters.team)}&min_ppg=${filters.minPpg}&max_ppg=${filters.maxPpg}`}>Cards</Link></div></div>{view === "cards" ? <div className="player-focus-card-grid">{players.length === 0 ? <p className="section-subtitle">No players match these filters.</p> : players.map((player) => <article className="player-focus-card" key={player.player_id}><div className="player-focus-headshot">{player.headshot ? <img src={player.headshot} alt="" /> : <span>?</span>}</div><div className="player-focus-info"><span className="eyebrow">{player.position ?? "--"} · {player.team_name ?? "--"}</span><h3>{`${player.first_name ?? ""} ${player.last_name ?? ""}`.trim()}</h3><div className="player-focus-stats"><strong>{formatNumber(player.ppg)}<span>PPG</span></strong><strong>{formatNumber(player.mpg)}<span>MPG</span></strong></div><span className="tag">Available</span></div></article>)}</div> : <div className="table-scroll"><table className="table"><thead><tr><th>Player</th><th>Team</th><th>Conference</th><th>Position</th><th>PPG</th><th>Status</th></tr></thead><tbody>{players.length === 0 ? <tr><td colSpan={6}>No players match these filters.</td></tr> : players.map((player) => <tr key={player.player_id}><td>{`${player.first_name ?? ""} ${player.last_name ?? ""}`.trim()}</td><td>{player.team_name ?? "--"}</td><td>{player.conference_name ?? "--"}</td><td>{player.position ?? "--"}</td><td>{formatNumber(player.ppg)}</td><td><span className="tag">Available</span></td></tr>)}</tbody></table></div>}</section>
  </div>;
}

