"use client";
import { useEffect, useMemo, useState } from "react";

const teams = ["MB", "AS", "SL", "DD", "Len", "Brandon", "John B", "BJ"];
function pickInfo(pickNumber) { if (pickNumber <= teams.length) return { pickNumber, roundNumber: 0, teamCode: teams[pickNumber - 1] }; const roundNumber = Math.floor((pickNumber - teams.length - 1) / teams.length) + 1; const slot = (pickNumber - teams.length - 1) % teams.length; return { pickNumber, roundNumber, teamCode: roundNumber % 2 === 1 ? teams[slot] : teams[teams.length - slot - 1] }; }

export default function DraftPickEntry({ history = null, readOnly = false }) {
  const [picks, setPicks] = useState([]); const [query, setQuery] = useState(""); const [results, setResults] = useState([]); const [selected, setSelected] = useState(null); const [focused, setFocused] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const historyPicks = useMemo(() => Object.values(history?.draftSlots || {}).map((player) => ({ pick_number: Number(player.pickNumber), team_code: player.teamCode, player_name: player.name, drafted_position: player.position, player_id: player.playerId })).sort((a, b) => a.pick_number - b.pick_number), [history]);
  const displayedPicks = readOnly ? historyPicks : picks; const next = useMemo(() => pickInfo(displayedPicks.length + 1), [displayedPicks.length]);
  const timeline = useMemo(() => Array.from({ length: 5 }, (_, offset) => { const pickNumber = Math.max(1, next.pickNumber - 2) + offset; const player = displayedPicks.find((pick) => pick.pick_number === pickNumber); return { ...pickInfo(pickNumber), teamCode: player?.team_code || pickInfo(pickNumber).teamCode, player, current: pickNumber === next.pickNumber }; }), [next.pickNumber, displayedPicks]);
  useEffect(() => { if (!readOnly) fetch("/api/draft-picks").then((response) => response.json()).then((data) => setPicks(data.picks || [])); }, [readOnly]);
  useEffect(() => { const timer = window.setTimeout(() => { fetch(`/api/draft-players?q=${encodeURIComponent(query)}`).then((response) => response.json()).then((data) => setResults(data.players || [])); }, 180); return () => window.clearTimeout(timer); }, [query]);
  async function submit() { if (!selected) return; setSaving(true); setMessage(""); const response = await fetch("/api/draft-picks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...next, playerId: selected.playerId, playerName: selected.name, draftedPosition: selected.position, collegeTeamName: selected.college, headshot: selected.headshot }) }); const data = await response.json(); if (!response.ok) setMessage(data.error || "Unable to save pick."); else { setPicks((current) => [...current, data.pick]); setSelected(null); setQuery(""); setResults([]); setMessage(`Saved Pick ${next.pickNumber}. ${next.teamCode} is now complete.`); window.dispatchEvent(new Event("draft-pick-saved")); } setSaving(false); }
  function searchBox() { return <div className="draft-pick-inline-search"><label>Search available players<input value={query} onFocus={() => setFocused(true)} onBlur={() => window.setTimeout(() => setFocused(false), 150)} onChange={(event) => setQuery(event.target.value)} placeholder="Search players…" /></label>{focused && results.length > 0 && <div className="draft-search-results">{results.map((player) => { const drafted = picks.some((pick) => Number(pick.player_id) === Number(player.playerId)); return <button type="button" disabled={drafted} className={`${selected?.playerId === player.playerId && selected?.position === player.position ? "selected" : ""} ${drafted ? "is-drafted" : ""}`} key={`${player.playerId}-${player.position}`} onClick={() => !drafted && setSelected(player)}><span className="draft-search-avatar">{player.headshot ? <img src={player.headshot} alt="" /> : "?"}</span><span><strong>{player.name}</strong><small>{player.college} · {player.position}{drafted ? " · Drafted" : ""}</small></span></button>; })}</div>}{selected && <div className="draft-inline-selected"><span className="draft-search-avatar"><img src={selected.headshot} alt="" /></span><div><strong>{selected.name}</strong><small>{selected.college} · Draft as {selected.position}</small></div><button className="solid-pill" type="button" disabled={saving} onClick={submit}>{saving ? "Saving…" : "Submit pick"}</button></div>}</div>; }
  return <section className="draft-pick-entry"><div className="draft-pick-timeline" aria-label="Draft pick timeline">{timeline.map((item) => <div className={`draft-pick-timeline-card ${item.current ? "is-current" : ""} ${item.player ? "is-complete" : "is-open"}`} key={item.pickNumber}><span>Pick {item.pickNumber}</span><strong>{item.teamCode}</strong><small>{item.roundNumber === 0 ? "Franchise Round" : `Round ${item.roundNumber}`}</small>{item.player ? <><div className="draft-pick-timeline-player"><span className="draft-pick-timeline-avatar"><img src={`https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/${item.player.player_id}.png`} alt="" /></span><b>{item.player.player_name}</b></div><em>{item.player.drafted_position}</em></> : item.current && !readOnly ? searchBox() : <b>{item.current ? "History complete" : "Open"}</b>}</div>)}</div>{message && <p className="draft-pick-message">{message}</p>}</section>;
}
