"use client";

import { useEffect, useMemo, useState } from "react";

const fmt = (value, digits = 1) => Number.isFinite(Number(value)) ? Number(value).toFixed(digits) : "—";
const metrics = [["PPG", "ppg"], ["MPG", "mpg"], ["Projected points", "projectedTotal"], ["Board rank", "rank"], ["Last 10 PPG", "roll10"], ["Games", "games"]];
function metricValue(key, value) { if (key === "rank" || key === "games") return Number(value) > 0 ? Math.round(Number(value)) : "—"; return fmt(value); }

export default function PickGame() {
  const [state, setState] = useState({ pairs: [], summary: null }); const [index, setIndex] = useState(0); const [confidence, setConfidence] = useState("3"); const [mode, setMode] = useState("practice"); const [includePlayed, setIncludePlayed] = useState(false); const [displayName, setDisplayName] = useState(""); const [visible, setVisible] = useState(new Set(["ppg", "mpg", "projectedTotal", "rank", "roll10", "games"])); const [result, setResult] = useState(null); const [loading, setLoading] = useState(true);
  async function load(nextIncludePlayed = includePlayed) { setLoading(true); const response = await fetch(`/api/picks?include_played=${nextIncludePlayed ? "1" : "0"}`); setState(await response.json()); setIndex(0); setResult(null); setLoading(false); }
  useEffect(() => { load(false); setDisplayName(window.localStorage.getItem("cbb_prediction_name") || ""); }, []);
  const pair = state.pairs[index]; const shownMetrics = useMemo(() => metrics.filter(([, key]) => visible.has(key)), [visible]);
  async function pick(side) { if (!pair) return; setLoading(true); const browserKey = window.localStorage.getItem("cbb_prediction_key") || crypto.randomUUID(); window.localStorage.setItem("cbb_prediction_key", browserKey); if (displayName.trim()) window.localStorage.setItem("cbb_prediction_name", displayName.trim()); const response = await fetch("/api/picks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pairId: pair.pairId, pickSide: side, confidence, mode, browserKey, displayName: displayName.trim() || "Anonymous" }) }); const payload = await response.json(); setResult({ ...payload, side }); setState((current) => ({ ...current, summary: payload.summary })); setLoading(false); }
  function next() { setIndex((current) => current + 1); setResult(null); }
  return <div className="page pick-page">
    <section className="pick-hero"><div><span className="tag">Human calibration lab</span><h1>Who would you draft?</h1><p>Make the call between two players from the blended 2026 board. Your picks help expose where the model is too high, too low, or missing context.</p></div><div className="pick-stats"><div><strong>{state.pairs.length}</strong><span>comparisons left</span></div><div><strong>{state.summary?.scoredPicks ?? 0}</strong><span>picks scored</span></div><div><strong>{state.summary?.accuracy == null ? "—" : `${fmt(state.summary.accuracy * 100)}%`}</strong><span>accuracy</span></div></div></section>
    <section className="pick-toolbar card"><label className="pick-control">Your name<input className="pick-name-input" value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="Optional nickname" /></label><label className="pick-control">Mode<select value={mode} onChange={(event) => setMode(event.target.value)}><option value="practice">Practice — reveal result</option><option value="collect">Collect — hide result</option></select></label><label className="pick-control">Queue<select value={includePlayed ? "all" : "new"} onChange={(event) => { const nextValue = event.target.value === "all"; setIncludePlayed(nextValue); load(nextValue); }}><option value="new">Unplayed only</option><option value="all">Include played</option></select></label><div className="confidence-control"><span>Confidence</span><div>{["1", "2", "3", "4", "5"].map((value) => <button key={value} type="button" className={confidence === value ? "active" : ""} onClick={() => setConfidence(value)}>{value}</button>)}</div></div><div className="metric-control"><span>Show stats</span><div>{metrics.map(([label, key]) => <label key={key}><input type="checkbox" checked={visible.has(key)} onChange={() => setVisible((current) => { const nextSet = new Set(current); nextSet.has(key) ? nextSet.delete(key) : nextSet.add(key); return nextSet; })} /> {label}</label>)}</div></div></section>
    {loading && !pair ? <div className="card pick-empty">Loading comparisons…</div> : !pair ? <div className="card pick-empty"><h2>Queue complete</h2><p>There are no more comparisons in this queue. Switch to “Include played” to review the board again.</p></div> : <><section className="pick-context"><div><span className="eyebrow">{pair.pairId}</span><span className="stat-pill">{pair.pairType.replaceAll("_", " ")}</span></div><p>{pair.reason}</p></section><section className="pick-board">{["A", "B"].map((side) => { const player = pair[side]; return <article className={`pick-player ${result?.side === side ? "selected" : ""}`} key={side}><div className="player-top"><div><span className="player-side">Player {side}</span><h2>{player.name}</h2><p>{player.team} · {player.rosterClass || "Roster class unknown"}</p></div><div className="rank-block"><strong>#{player.rank}</strong><span>board rank</span></div></div><div className="primary-stat"><strong>{fmt(player.projectedTotal)}</strong><span>projected remainder points</span></div><div className="pick-metrics">{shownMetrics.map(([label, key]) => <div key={key}><span>{label}</span><strong>{metricValue(key, player[key])}</strong></div>)}</div><button className="pick-button" type="button" disabled={Boolean(result) || loading} onClick={() => pick(side)}>Pick Player {side}</button></article>; })}</section><div className={`pick-result ${result ? (mode === "practice" ? (result.correct === "1" ? "good" : "bad") : "saved") : ""}`}>{result ? <><strong>{mode === "collect" ? "Pick saved" : result.correct === "1" ? "Correct call" : "Model disagreed"}</strong><span>{mode === "collect" ? "The actual result stays hidden for calibration." : `Actual winner: Player ${result.actualWinner}. Player A scored ${fmt(result.aActual)} and Player B scored ${fmt(result.bActual)}.`}</span><button className="solid-pill" onClick={next}>Next comparison</button></> : <span>Choose a player. Confidence {confidence}/5.</span>}</div></>}
  </div>;
}

